# Setup the environment:
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc++-dev
      - libx11-xcb-dev
      - libxrandr-dev

matrix:
  include:
    - compiler: clang
    - compiler: gcc
      env: TARGETS="compiler-gcc"

install:
  - gem install teapot

# Run tests:
script:
  - teapot fetch
  - teapot build Test/Vizor $TARGETS
