# Setup the environment:
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - ppa:paulo-miguel-dias/mesa
    packages:
      - libc++-dev
      - libx11-xcb-dev
      - libxrandr-dev
      - xserver-xorg-video-intel

matrix:
  include:
    - compiler: clang
    - compiler: gcc
      env: TARGETS="compiler-gcc"

install:
  - gem install teapot

# Run tests:
script:
  - teapot fetch
  - teapot build Test/Vizor $TARGETS
