# Setup the environment:
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc++-dev
      - libx11-xcb-dev
      - libxrandr-dev
      - mesa-vulkan-drivers
      - vulkan-utils

matrix:
  include:
    - compiler: clang
    - compiler: gcc
      env: TARGETS="compiler-gcc"
    - compiler: clang
      os: osx

install:
  - gem install teapot

# Run tests:
script:
  - teapot fetch
  - teapot build Test/Vizor $TARGETS
