name: Test

on: [push]

jobs:
  test:
    # Run it on GPU enabled host:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: Fetch packages
      run: teapot fetch
    - name: Run tests
      run: teapot Test/Vizor compiler-gcc
